#!/bin/bash

app=phpBB

# Retrieve arguments
domain=$1
path=$2
is_public=$3
admin_login=$4
admin_pwd=$5
admin_email=$6
lang=$7

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

db_user=$app
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')
#db_pwd=$admin_pwd

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting $app mysqlpwd -v $db_pwd
sudo yunohost app setting $app admin_login -v $admin_login
sudo yunohost app setting $app admin_pwd -v $admin_pwd
sudo yunohost app setting $app admin_email -v $admin_email

# Copy files to the right place
final_path=/var/www/$app
sudo rm -rf $final_path
sudo mkdir -p $final_path
sudo cp -a ../sources/phpBB/* $final_path

# We add french language pack
if [ "$lang" = "fr" ];
	then sudo cp -a ../sources/french_language/* $final_path/
fi

# Set permissions to working directory
sudo chown -R www-data:www-data $final_path

# phpBB requires imagemagick to manipulate pictures
sudo apt-get update -qq > /dev/null 2>&1
sudo apt-get install -y imagemagick > /dev/null 2>&1


# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

sed -i "s@NAMETOCHANGE@$app@g" ../conf/php-fpm.conf
finalphpconf=/etc/php5/fpm/pool.d/$app.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
sudo chmod 644 $finalphpconf

# Make app public if necessary
sudo yunohost app setting $app is_public -v "$is_public"
if [ "$is_public" = "Yes" ];
then
    sudo yunohost app setting $app skipped_uris -v "/"
fi


# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm reload
sudo service nginx reload
sudo yunohost app ssowatconf


