#!/bin/bash

#db_user=rainloop
#db_name=rainloop
#root_pwd=$(sudo cat /etc/yunohost/mysql)
app=phpBB
domain=$(sudo yunohost app setting $app domain)

#mysql -u root -p $root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"
sudo rm -rf /var/www/$app
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /etc/php5/fpm/pool.d/$app.conf

sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf

